CREATE SCHEMA IF NOT EXISTS `BlogDB`;
USE `BlogDB`;

CREATE TABLE IF NOT EXISTS `BlogDB`.`posts` (
    `id` INT NOT NULL AUTO INCREMENT,
    `owner` INT NOT NULL AUTO INCREMENT,
    `title` INT NOT NULL AUTO INCREMENT,
    `body` MEDIUMTEXT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB;